version: '3'
services:
  flitserdata:
    container_name: flitserdata
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    entrypoint: /app/entrypoint.sh
    command: uvicorn app:app --reload --host 0.0.0.0
    depends_on:
      - testdb

  cronjobs:
    container_name: cronjobs
    build:
      context: .
      dockerfile: Dockerfile-cron.dev
    volumes:
      - .:/cron
    env_file:
      - .env
    depends_on:
      - testdb

  testdb:
    image: postgres:11-alpine
    container_name: testdb
    restart: always
    volumes:
      - ./migration_scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    env_file:
      - .env-db
    healthcheck:
      test: pg_isready

  jupyter:
    container_name: flitsers_jupyter
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
      - ./notebook/config/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py
      - ./notebook/config/kernel.json:/opt/conda/share/jupyter/kernels/python3/kernel.json
      - ./notebook/work:/home/jovyan/work
      - ./notebook/data:/home/jovyan/data
    ports:
      - "8888:8888"
    env_file:
      - .env-db
      - .env-jupyter
