#################################################################
# Dockerfile to build test container for cron jobs
#################################################################
FROM python:3.11

WORKDIR cron

RUN apt-get update \
    && apt-get install -y build-essential bash cron vim tor \
    && pip3 install --upgrade pip setuptools

COPY pyproject.toml poetry.lock ./

RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3 -

ENV PATH="$PATH:/root/.local/bin"

RUN poetry config virtualenvs.create false
RUN poetry install

COPY ./app/model.py /cron/
COPY ./app/scraper.py /cron/
COPY ./app/scrapefunctions.py /cron/
COPY ./app/consts.py /cron/

CMD tor
